### ISSUE TITLE
Work on a logo

### ISSUE THREAD

**Issue by mrahhal** [mrahhal/niai#20]

**Comment by Tobaloidee** [comment]
@mrahhal I can do a logo for this project. I am a graphic artist. -[Tobaloidee](https://steemit.com/@tobaloidee)

**Comment by mrahhal** [comment]
@Tobaloidee that would be great! Ask me about anything when you want to get this started.

**Comment by Tobaloidee** [comment]
@mrahhal  upon reading the project description, it's mainly about searching for words like thesaurus? I just need to know the main function of the project 😊

**Comment by mrahhal** [comment]
It's for Japanese learners, it's mainly for looking up "similar things" which include similar kanjis, homonyms, synonyms. So it's a bit different than a thesaurus (apart from probably synonyms). Feel free to check the website here as well: http://niai.mrahhal.net

To be honest I have no idea how a logo would look like, but maybe something kinda similar to [Google Translate's logo](https://www.google.com/search?q=google+translate+logo&rlz=1C1CHBF_enLB835LB835&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiSz5rLu9HhAhWm1uAKHd0XCoEQ_AUIDigB&biw=1862&bih=948&dpr=1.38#imgrc=B0YOMdCkbOK0MM:) but with 2 similar looking kanjis? But I'm open to anything. 

(Note just in case: Kanjis are one of the writing systems of Japanese and it encompasses more than 2.1K characters, a lot of which are very similar.)

**Comment by Tobaloidee** [comment]
Thank you for the information, will work on it and show you here after 👍

**Comment by Tobaloidee** [comment]
Hello @mrahhal  here's what I came up with for your project's logo. I hope you like it!

- I created a simple and unique logo design customized to be more memorable and functional


![niai-01](https://user-images.githubusercontent.com/36028424/56196047-ab668a00-6068-11e9-89f1-f04adfbe04f0.png)

**Comment by mrahhal** [comment]
Hello @Tobaloidee. This is actually really nice! Simple and meaningful.

This site has a dark mode too, do you think this version will be enough in both light and dark backgrounds? (You can check the dark mode by toggling the icon in the bottom left corner of the sidebar)

**Comment by Tobaloidee** [comment]
Yes it will work on dark background too! i will show you when I get home..I am here work now..Im glad that you like it!😃👍

**Comment by Tobaloidee** [comment]
I updated the display to show you the implementation in dark background @mrahhal

**Comment by mrahhal** [comment]
Looks good 👍 👍

**Comment by Tobaloidee** [comment]
Will finalize the files and make a PR tom for the logo! 👍😀

**Comment by mrahhal** [comment]
Thanks! 😄

**Comment by Tobaloidee** [comment]
Hi @mrahhal  Here's the PR #27 with the logo upload and readme update... And also, you can download all the other versions & formats of your logo on this [LINK](https://drive.google.com/drive/u/1/folders/1icTLmyfFnG7G78DgKo0hMSZ4VXBOeOrU)

Thanks and Best Regards!

-Tobaloidee

**Comment by mrahhal** [comment]
Awesome, thanks a lot!
