### ISSUE TITLE
Question: Similar Kanji

### ISSUE THREAD

**Issue by MarcusAseth** [mrahhal/niai#39]
Hi, I had a curiosity about the Similar Kanji data - it is something handcrafted for this app or is something free (like jmdict) that I can obtain and use myself? 
If it is the second, where I can get it? ^_^

**Comment by mrahhal** [comment]
Hi. There's no similar kanji databases. It's just a score I compute following a certain algorithm from various different databases, one of which gives the kanji components. And I change it from time to time. It's all in the Aggregator project in this repo, feel free to check it out.

**Comment by MarcusAseth** [comment]
thanks :)
